services:
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db

  nodeapp:
    build:
      context: ./node-app
      dockerfile: ../Dockerfile
    develop:
      watch:
      - action: rebuild
        path: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
